# Generated by Django 4.0.4 on 2022-06-15 08:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.ManyToManyField(related_name='watched', to='auctions.listing')),
                ('user', models.ManyToManyField(related_name='watchers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
